// Large NSE Universe - Small Cap + Mid Cap + Large Cap + Others (380+ stocks)
export interface StockMeta {
  symbol: string;
  name: string;
}

export const NSE_UNIVERSE: StockMeta[] = [
  // Large Caps
  { symbol: "RELIANCE", name: "Reliance Industries" },
  { symbol: "TCS", name: "Tata Consultancy Services" },
  { symbol: "HDFCBANK", name: "HDFC Bank" },
  { symbol: "ICICIBANK", name: "ICICI Bank" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel" },
  { symbol: "SBIN", name: "State Bank of India" },
  { symbol: "INFY", name: "Infosys" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever" },
  { symbol: "ITC", name: "ITC Ltd" },
  { symbol: "HCLTECH", name: "HCL Technologies" },
  { symbol: "AXISBANK", name: "Axis Bank" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance" },
  { symbol: "MARUTI", name: "Maruti Suzuki India" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical" },
  { symbol: "TITAN", name: "Titan Company" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement" },
  { symbol: "NTPC", name: "NTPC Ltd" },
  { symbol: "POWERGRID", name: "Power Grid Corporation" },
  { symbol: "M&M", name: "Mahindra & Mahindra" },
  { symbol: "TATAMOTORS", name: "Tata Motors" },
  { symbol: "WIPRO", name: "Wipro" },
  { symbol: "ADANIENT", name: "Adani Enterprises" },
  { symbol: "ADANIPORTS", name: "Adani Ports" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv" },
  { symbol: "COALINDIA", name: "Coal India" },
  { symbol: "ONGC", name: "Oil & Natural Gas Corp" },
  { symbol: "TATASTEEL", name: "Tata Steel" },
  { symbol: "JSWSTEEL", name: "JSW Steel" },
  { symbol: "HINDALCO", name: "Hindalco Industries" },
  { symbol: "SHRIRAMFIN", name: "Shriram Finance" },
  { symbol: "GRASIM", name: "Grasim Industries" },
  { symbol: "TECHM", name: "Tech Mahindra" },
  { symbol: "CIPLA", name: "Cipla" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories" },
  { symbol: "EICHERMOT", name: "Eicher Motors" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories" },
  { symbol: "BRITANNIA", name: "Britannia Industries" },

  // Mid Caps
  { symbol: "PIDILITIND", name: "Pidilite Industries" },
  { symbol: "SIEMENS", name: "Siemens" },
  { symbol: "HAVELLS", name: "Havells India" },
  { symbol: "DABUR", name: "Dabur India" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products" },
  { symbol: "MARICO", name: "Marico" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India" },
  { symbol: "BERGEPAINT", name: "Berger Paints India" },
  { symbol: "UPL", name: "UPL Ltd" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals" },
  { symbol: "LUPIN", name: "Lupin" },
  { symbol: "ALKEM", name: "Alkem Laboratories" },
  { symbol: "AUBANK", name: "AU Small Finance Bank" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank" },
  { symbol: "FEDERALBNK", name: "Federal Bank" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank" },
  { symbol: "PNB", name: "Punjab National Bank" },
  { symbol: "BANKBARODA", name: "Bank of Baroda" },
  { symbol: "CANBK", name: "Canara Bank" },
  { symbol: "UNIONBANK", name: "Union Bank of India" },
  { symbol: "IOB", name: "Indian Overseas Bank" },
  { symbol: "CUB", name: "City Union Bank" },
  { symbol: "RBLBANK", name: "RBL Bank" },
  { symbol: "YESBANK", name: "Yes Bank" },
  { symbol: "INDIANB", name: "Indian Bank" },
  { symbol: "BSE", name: "BSE Ltd" },
  { symbol: "MCX", name: "Multi Commodity Exchange" },
  { symbol: "IRCTC", name: "Indian Railway Catering" },
  { symbol: "IRFC", name: "Indian Railway Finance" },
  { symbol: "RVNL", name: "Rail Vikas Nigam" },
  { symbol: "IRCON", name: "IRCON International" },
  { symbol: "CONCOR", name: "Container Corporation" },
  { symbol: "GMRINFRA", name: "GMR Airports Infrastructure" },
  { symbol: "ADANIPOWER", name: "Adani Power" },
  { symbol: "TATAPOWER", name: "Tata Power" },
  { symbol: "POWERINDIA", name: "Power India" },
  { symbol: "CGPOWER", name: "CG Power and Industrial" },
  { symbol: "VOLTAS", name: "Voltas" },
  { symbol: "BLUESTARCO", name: "Blue Star" },
  { symbol: "CUMMINSIND", name: "Cummins India" },
  { symbol: "THERMAX", name: "Thermax" },
  { symbol: "AIAENG", name: "AIA Engineering" },
  { symbol: "BEL", name: "Bharat Electronics" },
  { symbol: "HAL", name: "Hindustan Aeronautics" },
  { symbol: "BEML", name: "BEML Ltd" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals" },
  { symbol: "SAIL", name: "Steel Authority of India" },
  { symbol: "NMDC", name: "NMDC Ltd" },
  { symbol: "MOIL", name: "MOIL Ltd" },
  { symbol: "NATIONALUM", name: "National Aluminium" },
  { symbol: "HINDZINC", name: "Hindustan Zinc" },
  { symbol: "VEDL", name: "Vedanta" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power" },
  { symbol: "JSWENERGY", name: "JSW Energy" },
  { symbol: "NTPCGREEN", name: "NTPC Green Energy" },
  { symbol: "RECLTD", name: "REC Ltd" },
  { symbol: "PFC", name: "Power Finance Corporation" },
  { symbol: "HUDCO", name: "Housing & Urban Development" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson" },
  { symbol: "BOSCHLTD", name: "Bosch" },
  { symbol: "SCHAEFFLER", name: "Schaeffler India" },
  { symbol: "SKFINDIA", name: "SKF India" },
  { symbol: "TIMKEN", name: "Timken India" },
  { symbol: "EXIDEIND", name: "Exide Industries" },
  { symbol: "AMARAJABAT", name: "Amara Raja Energy" },
  { symbol: "SUPREMEIND", name: "Supreme Industries" },
  { symbol: "ASTRAL", name: "Astral" },
  { symbol: "POLYCAB", name: "Polycab India" },
  { symbol: "KEI", name: "KEI Industries" },
  { symbol: "FINPIPE", name: "Finolex Pipes" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes" },
  { symbol: "JSL", name: "Jindal Stainless" },
  { symbol: "SAREGAMA", name: "Saregama India" },
  { symbol: "PVRINOX", name: "PVR Inox" },
  { symbol: "ZEEL", name: "Zee Entertainment" },
  { symbol: "SUNTV", name: "Sun TV Network" },
  { symbol: "NAUKRI", name: "Info Edge (Naukri)" },
  { symbol: "ZOMATO", name: "Zomato" },
  { symbol: "PAYTM", name: "One97 Communications" },
  { symbol: "NYKAA", name: "FSN E-Commerce" },
  { symbol: "SWIGGY", name: "Swiggy" },
  { symbol: "DELHIVERY", name: "Delhivery" },
  { symbol: "EASEMYTRIP", name: "Easy Trip Planners" },
  { symbol: "AFFLE", name: "Affle India" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds" },
  { symbol: "PERSISTENT", name: "Persistent Systems" },
  { symbol: "COFORGE", name: "Coforge" },
  { symbol: "LTIM", name: "LTIMindtree" },
  { symbol: "MPHASIS", name: "Mphasis" },
  { symbol: "LTTS", name: "L&T Technology Services" },
  { symbol: "CYIENT", name: "Cyient" },
  { symbol: "TATAELXSI", name: "Tata Elxsi" },
  { symbol: "KPITTECH", name: "KPIT Technologies" },
  { symbol: "SONATSOFTW", name: "Sonata Software" },
  { symbol: "INTELLECT", name: "Intellect Design Arena" },
  { symbol: "FORTIS", name: "Fortis Healthcare" },
  { symbol: "MAXHEALTH", name: "Max Healthcare" },
  { symbol: "MEDANTA", name: "Global Health (Medanta)" },
  { symbol: "KIMS", name: "Krishna Institute of Medical" },
  { symbol: "NARAYANA", name: "Narayana Hrudayalaya" },
  { symbol: "JUBLFOOD", name: "Jubilant FoodWorks" },
  { symbol: "DEVYANI", name: "Devyani International" },
  { symbol: "WESTLIFE", name: "Westlife Development" },
  { symbol: "SAPPHIRE", name: "Sapphire Foods" },
  { symbol: "RESTAURANT", name: "Restaurant Brands Asia" },
  { symbol: "PAGEIND", name: "Page Industries" },
  { symbol: "ABFRL", name: "Aditya Birla Fashion" },
  { symbol: "TRENT", name: "Trent Ltd" },
  { symbol: "VMART", name: "V-Mart Retail" },
  { symbol: "MANYAVAR", name: "Vedant Fashions (Manyavar)" },
  { symbol: "KALYANKJIL", name: "Kalyan Jewellers" },
  { symbol: "SJS", name: "SJS Enterprises" },
  { symbol: "CERA", name: "Cera Sanitaryware" },
  { symbol: "KPRMILL", name: "K.P.R. Mill" },
  { symbol: "WELSPUNLIV", name: "Welspun Living" },
  { symbol: "TRIDENT", name: "Trident Ltd" },
  { symbol: "ARVIND", name: "Arvind Ltd" },
  { symbol: "RAYMOND", name: "Raymond" },
  { symbol: "SIYSIL", name: "Siyaram Silk Mills" },
  { symbol: "VRLLOG", name: "VRL Logistics" },
  { symbol: "BLUEDART", name: "Blue Dart Express" },
  { symbol: "TATAINVEST", name: "Tata Investment" },
  { symbol: "BAJAJHLDNG", name: "Bajaj Holdings" },
  { symbol: "MFSL", name: "Max Financial Services" },
  { symbol: "ICICIPRULI", name: "ICICI Prudential Life" },
  { symbol: "SBILIFE", name: "SBI Life Insurance" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance" },
  { symbol: "NIPPONLIFE", name: "Nippon Life India AMC" },
  { symbol: "ABSLAMC", name: "Aditya Birla Sun Life AMC" },
  { symbol: "UTIAMC", name: "UTI Asset Management" },
  { symbol: "CDSL", name: "Central Depository Services" },
  { symbol: "CAMLINFINE", name: "Camlin Fine Sciences" },
  { symbol: "FINEORG", name: "Fine Organic Industries" },
  { symbol: "ALKYLAMINE", name: "Alkyl Amines Chemicals" },
  { symbol: "VINATIORGA", name: "Vinati Organics" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine" },
  { symbol: "FLUOROCHEM", name: "Gujarat Fluorochemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite" },
  { symbol: "ATUL", name: "Atul Ltd" },
  { symbol: "PIIND", name: "PI Industries" },
  { symbol: "SUMICHEM", name: "Sumitomo Chemical India" },
  { symbol: "COROMANDEL", name: "Coromandel International" },
  { symbol: "BAYERCROP", name: "Bayer CropScience" },
  { symbol: "CHAMBLFERT", name: "Chambal Fertilisers" },
  { symbol: "FACT", name: "Fertilizers & Chemicals" },
  { symbol: "GSFC", name: "Gujarat State Fertilizers" },
  { symbol: "GNFC", name: "Gujarat Narmada Valley" },
  { symbol: "RCF", name: "Rashtriya Chemicals" },
  { symbol: "NFL", name: "National Fertilizers" },
  { symbol: "MGL", name: "Mahanagar Gas" },
  { symbol: "IGL", name: "Indraprastha Gas" },
  { symbol: "GUJGASLTD", name: "Gujarat Gas" },
  { symbol: "GSPL", name: "Gujarat State Petronet" },
  { symbol: "PETRONET", name: "Petronet LNG" },
  { symbol: "OIL", name: "Oil India" },
  { symbol: "BPCL", name: "Bharat Petroleum" },
  { symbol: "HINDPETRO", name: "Hindustan Petroleum" },
  { symbol: "IOC", name: "Indian Oil Corporation" },
  { symbol: "MRPL", name: "Mangalore Refinery" },
  { symbol: "CASTROLIND", name: "Castrol India" },
  { symbol: "GULFOILLUB", name: "Gulf Oil Lubricants" },
  { symbol: "AEGISCHEM", name: "Aegis Logistics" },
  { symbol: "ALLCARGO", name: "Allcargo Logistics" },
  { symbol: "GESHIP", name: "Great Eastern Shipping" },
  { symbol: "SCI", name: "Shipping Corporation" },
  { symbol: "COCHINSHIP", name: "Cochin Shipyard" },
  { symbol: "GRSE", name: "Garden Reach Shipbuilders" },
  { symbol: "MAZDOCK", name: "Mazagon Dock Shipbuilders" },
  { symbol: "LLOYDSME", name: "Lloyds Metals & Energy" },
  { symbol: "KIOCL", name: "KIOCL Ltd" },
  { symbol: "NLCINDIA", name: "NLC India" },
  { symbol: "NBCC", name: "NBCC (India)" },
  { symbol: "IRB", name: "IRB Infrastructure" },
  { symbol: "PNCINFRA", name: "PNC Infratech" },
  { symbol: "KNRCON", name: "KNR Constructions" },
  { symbol: "NCC", name: "NCC Ltd" },
  { symbol: "LT", name: "Larsen & Toubro" },
  { symbol: "KEC", name: "KEC International" },
  { symbol: "KALPATPOWR", name: "Kalpataru Power" },
  { symbol: "TATAELXSI", name: "Tata Elxsi" },
  { symbol: "PERSISTENT", name: "Persistent Systems" },

  // Small Caps & Others (high liquidity small/mid)
  { symbol: "JUBLINGREA", name: "Jubilant Ingrevia" },
  { symbol: "JUBLPHARMA", name: "Jubilant Pharmova" },
  { symbol: "GRANULES", name: "Granules India" },
  { symbol: "LAURUSLABS", name: "Laurus Labs" },
  { symbol: "METROPOLIS", name: "Metropolis Healthcare" },
  { symbol: "THYROCARE", name: "Thyrocare Technologies" },
  { symbol: "VIJAYA", name: "Vijaya Diagnostic Centre" },
  { symbol: "DRAGARWAL", name: "Dr. Agarwal's Eye Hospital" },
  { symbol: "STAR", name: "Strides Pharma" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals" },
  { symbol: "IPCALAB", name: "IPCA Laboratories" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma" },
  { symbol: "ERIS", name: "Eris Lifesciences" },
  { symbol: "GLAND", name: "Gland Pharma" },
  { symbol: "SUVENPHAR", name: "Suven Pharmaceuticals" },
  { symbol: "FDC", name: "FDC Ltd" },
  { symbol: "CAPLIPOINT", name: "Caplin Point Laboratories" },
  { symbol: "MARKSANS", name: "Marksans Pharma" },
  { symbol: "AARTIDRUGS", name: "Aarti Drugs" },
  { symbol: "SEQUENT", name: "Sequent Scientific" },
  { symbol: "THELEELA", name: "The Leela Palaces" },
  { symbol: "EIHOTEL", name: "EIH Ltd (Oberoi)" },
  { symbol: "INDHOTEL", name: "Indian Hotels" },
  { symbol: "LEMONTREE", name: "Lemon Tree Hotels" },
  { symbol: "TAJGVK", name: "Taj GVK Hotels" },
  { symbol: "ORIENTCEM", name: "Orient Cement" },
  { symbol: "JKCEMENT", name: "JK Cement" },
  { symbol: "RAMCOCEM", name: "Ramco Cements" },
  { symbol: "PRSMJOHNSN", name: "Prism Johnson" },
  { symbol: "ACC", name: "ACC Ltd" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements" },
  { symbol: "SHREECEM", name: "Shree Cement" },
  { symbol: "INDIACEM", name: "India Cements" },
  { symbol: "JKLAKSHMI", name: "JK Lakshmi Cement" },
  { symbol: "BIRLACORPN", name: "Birla Corporation" },
  { symbol: "STARCEMENT", name: "Star Cement" },
  { symbol: "HEIDELBERG", name: "HeidelbergCement India" },
  { symbol: "SAGCEM", name: "Sagar Cements" },
  { symbol: "PRESTIGE", name: "Prestige Estates" },
  { symbol: "GODREJPROP", name: "Godrej Properties" },
  { symbol: "BRIGADE", name: "Brigade Enterprises" },
  { symbol: "SOBHA", name: "Sobha Ltd" },
  { symbol: "MAHLIFE", name: "Mahindra Lifespace" },
  { symbol: "OberoiRealty", name: "Oberoi Realty" },
  { symbol: "SUNTECK", name: "Sunteck Realty" },
  { symbol: "PHOENIXLTD", name: "Phoenix Mills" },
  { symbol: "DLF", name: "DLF Ltd" },
  { symbol: "LODHA", name: "Macrotech Developers" },
  { symbol: "EMBDL", name: "Embassy Office Parks REIT" },
  { symbol: "MINDSPACE", name: "Mindspace Business Parks REIT" },
  { symbol: "BROOKFIELD", name: "Brookfield India REIT" },
  { symbol: "NEXG", name: "NexGen" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics" },
  { symbol: "ROUTE", name: "Route Mobile" },
  { symbol: "TANLA", name: "Tanla Platforms" },
  { symbol: "QUESS", name: "Quess Corp" },
  { symbol: "TEAMLEASE", name: "TeamLease Services" },
  { symbol: "SIS", name: "SIS Ltd" },
  { symbol: "ALLSEC", name: "Allsec Technologies" },
  { symbol: "SYNGENE", name: "Syngene International" },
  { symbol: "JUBILANT", name: "Jubilant Life Sciences" },
  { symbol: "DIXON", name: "Dixon Technologies" },
  { symbol: "AMBER", name: "Amber Enterprises" },
  { symbol: "SYRMA", name: "Syrma SGS Technology" },
  { symbol: "KAYNES", name: "Kaynes Technology" },
  { symbol: "PGEL", name: "PG Electroplast" },
  { symbol: "CENTURYPLY", name: "Century Plyboards" },
  { symbol: "GREENLAM", name: "Greenlam Industries" },
  { symbol: "GREENPLY", name: "Greenply Industries" },
  { symbol: "ARCHIDPLY", name: "Archidply Industries" },
  { symbol: "STYLAMIND", name: "Stylam Industries" },
  { symbol: "NILKAMAL", name: "Nilkamal" },
  { symbol: "VIPIND", name: "VIP Industries" },
  { symbol: "BATAINDIA", name: "Bata India" },
  { symbol: "RELAXO", name: "Relaxo Footwears" },
  { symbol: "CAMPUS", name: "Campus Activewear" },
  { symbol: "LIBERTSHOE", name: "Liberty Shoes" },
  { symbol: "MIRZAINT", name: "Mirza International" },
  { symbol: "SUPERHOUSE", name: "Superhouse" },
  { symbol: "GUFICBIO", name: "Gufic Biosciences" },
  { symbol: "PANACEABIO", name: "Panacea Biotec" },
  { symbol: "VIRINCHI", name: "Virinchi Technologies" },
  { symbol: "RAMKY", name: "Ramky Infrastructure" },
  { symbol: "PNCINFRA", name: "PNC Infratech" },
  { symbol: "WELCORP", name: "Welspun Corp" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper" },
  { symbol: "GRAVITA", name: "Gravita India" },
  { symbol: "MMTC", name: "MMTC Ltd" },
  { symbol: "STCINDIA", name: "State Trading Corp" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries" },
  { symbol: "CEATLTD", name: "CEAT Ltd" },
  { symbol: "TVSSRICHAK", name: "TVS Srichakra" },
  { symbol: "GOODYEAR", name: "Goodyear India" },
  { symbol: "MRF", name: "MRF Ltd" },
  { symbol: "TATACOMM", name: "Tata Communications" },
  { symbol: "TATAELXSI", name: "Tata Elxsi" },
  { symbol: "CYIENT", name: "Cyient" },
  { symbol: "KPITTECH", name: "KPIT Technologies" },
  { symbol: "SONATSOFTW", name: "Sonata Software" },
  { symbol: "INTELLECT", name: "Intellect Design" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds" },
  { symbol: "AFFLE", name: "Affle India" },
  { symbol: "ROUTE", name: "Route Mobile" },
  { symbol: "TANLA", name: "Tanla Platforms" },
  { symbol: "QUESS", name: "Quess Corp" },
  { symbol: "TEAMLEASE", name: "TeamLease Services" },
  { symbol: "SIS", name: "SIS Ltd" },
  { symbol: "ALLSEC", name: "Allsec Technologies" },
  { symbol: "SYNGENE", name: "Syngene International" },
  { symbol: "LATENTVIEW", name: "Latent View Analytics" },
  { symbol: "DIXON", name: "Dixon Technologies" },
  { symbol: "AMBER", name: "Amber Enterprises" },
  { symbol: "SYRMA", name: "Syrma SGS Technology" },
  { symbol: "KAYNES", name: "Kaynes Technology" },
  { symbol: "PGEL", name: "PG Electroplast" },
  { symbol: "CENTURYPLY", name: "Century Plyboards" },
  { symbol: "GREENLAM", name: "Greenlam Industries" },
  { symbol: "GREENPLY", name: "Greenply Industries" },
  { symbol: "ARCHIDPLY", name: "Archidply Industries" },
  { symbol: "STYLAMIND", name: "Stylam Industries" },
  { symbol: "NILKAMAL", name: "Nilkamal" },
  { symbol: "VIPIND", name: "VIP Industries" },
  { symbol: "BATAINDIA", name: "Bata India" },
  { symbol: "RELAXO", name: "Relaxo Footwears" },
  { symbol: "CAMPUS", name: "Campus Activewear" },
  { symbol: "LIBERTSHOE", name: "Liberty Shoes" },
  { symbol: "MIRZAINT", name: "Mirza International" },
  { symbol: "SUPERHOUSE", name: "Superhouse" },
  { symbol: "GUFICBIO", name: "Gufic Biosciences" },
  { symbol: "PANACEABIO", name: "Panacea Biotec" },
  { symbol: "VIRINCHI", name: "Virinchi Technologies" },
  { symbol: "RAMKY", name: "Ramky Infrastructure" },
  { symbol: "WELCORP", name: "Welspun Corp" },
  { symbol: "HINDCOPPER", name: "Hindustan Copper" },
  { symbol: "GRAVITA", name: "Gravita India" },
  { symbol: "MMTC", name: "MMTC Ltd" },
  { symbol: "STCINDIA", name: "State Trading Corp" },
  { symbol: "BALKRISIND", name: "Balkrishna Industries" },
  { symbol: "APOLLOTYRE", name: "Apollo Tyres" },
  { symbol: "JKTYRE", name: "JK Tyre & Industries" },
  { symbol: "CEATLTD", name: "CEAT Ltd" },
  { symbol: "TVSSRICHAK", name: "TVS Srichakra" },
  { symbol: "GOODYEAR", name: "Goodyear India" },
  { symbol: "MRF", name: "MRF Ltd" },
  { symbol: "TATACOMM", name: "Tata Communications" },
  { symbol: "VBL", name: "Varun Beverages" },
  { symbol: "JIOFIN", name: "Jio Financial Services" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital" },
  { symbol: "MOTHERSON", name: "Samvardhana Motherson" },
  { symbol: "TMCV", name: "Tata Motors CV" },
  { symbol: "TMPV", name: "Tata Motors PV" },
  { symbol: "BANKINDIA", name: "Bank of India" },
  { symbol: "CENTRALBK", name: "Central Bank of India" },
  { symbol: "UCOBANK", name: "UCO Bank" },
  { symbol: "MAHABANK", name: "Bank of Maharashtra" },
  { symbol: "PSUBANK", name: "PSU Bank ETF" },
];

export function toYahooSymbol(symbol: string): string {
  const s = symbol.toUpperCase().trim();
  return s.endsWith(".NS") ? s : `${s}.NS`;
}

export function shortSymbol(symbol: string): string {
  return symbol.replace(".NS", "");
}
